#!/bin/bash
set -euxo pipefail

# Task 1 & 3 Checks
jq < /solutions/data.json
jq -e '.cve == "CVE-2025-32463"' < /solutions/data.json

# Task 2 Checks
terraform fmt /solutions/data.tf

hcl2json /solutions/data.tf | jq > /tmp/data.tf.json

jq -e '.data.hcp_packer_artifact["app-ubuntu"][0].bucket_name == "app-ubuntu"' < /tmp/data.tf.json
jq -e '.data.hcp_packer_artifact["app-ubuntu"][0].channel_name == "latest"' < /tmp/data.tf.json
jq -e '.data.hcp_packer_artifact["app-ubuntu"][0].platform == "aws"' < /tmp/data.tf.json
jq -e '.data.hcp_packer_artifact["app-ubuntu"][0].region == "us-west-2"' < /tmp/data.tf.json
