version: "3"
containers:
- name: sandbox
  image: ghcr.io/hashicorp-dev-advocates/hashiconf-escape-room:main
  shell: /bin/bash
  environment:
    BOUNDARY_ADDR: SECRET
    BOUNDARY_PASSWORD: SECRET
    BOUNDARY_USER: SECRET
    CIPHERTEXT: SECRET
    CONSUL_HTTP_ADDR: SECRET
    CONSUL_HTTP_TOKEN: SECRET
    CONTEXT: SECRET
    VAULT_ADDR: SECRET
    VAULT_NAMESPACE: SECRET
    VAULT_PASSWORD: SECRET
    VAULT_USER: SECRET
  memory: 256
