name: HCP Packer

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/packer.yaml
      - packer/app-ubuntu/**

permissions:
  id-token: write
  contents: read

jobs:
  app-ubuntu:
    runs-on: ubuntu-latest
    name: app-ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          role-session-name: github-to-aws-packer-build
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup `packer`
        uses: hashicorp/setup-packer@v3
        id: setup
        with:
          version: "latest"

      - name: Run `packer init`
        id: init
        run: "packer init ."
        working-directory: ./packer/app-ubuntu

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."
        working-directory: ./packer/app-ubuntu

      - name: Build Artifact
        run: packer build -color=false .
        working-directory: ./packer/app-ubuntu
        env:
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          HCP_PACKER_BUILD_FINGERPRINT: "run.id.${{ github.run_id }}.run.attempt.${{ github.run_attempt }}"
          HCP_PACKER_BUILD_DETAILS: "Look under the mug on the shelf."